//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_mixedreality : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose RightController
        {
            get
            {
                return SteamVR_Actions.mixedreality_RightController;
            }
        }
        
        public virtual SteamVR_Action_Pose LeftController
        {
            get
            {
                return SteamVR_Actions.mixedreality_LeftController;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightTrigger
        {
            get
            {
                return SteamVR_Actions.mixedreality_RightTrigger;
            }
        }
        
        public virtual SteamVR_Action_Vector2 LeftTouchpad
        {
            get
            {
                return SteamVR_Actions.mixedreality_LeftTouchpad;
            }
        }
        
        public virtual SteamVR_Action_Pose RightControllerTop
        {
            get
            {
                return SteamVR_Actions.mixedreality_RightControllerTop;
            }
        }
        
        public virtual SteamVR_Action_Boolean RightMenu
        {
            get
            {
                return SteamVR_Actions.mixedreality_RightMenu;
            }
        }
    }
}
